# Basic kitting config

options:
  insert_models_over_bins: true
  insert_models_over_stations: false
  belt_population_cycles: 0
  time_limit: -1

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: as2
  agv3:
    location: as3
  agv4:
    location: as4   

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_regulator_red
          pose:
            xyz: [0.15, 0.0, 0]
            rpy: [0, 0, 'pi/4']

          
models_over_bins:
   bin1:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
   bin4:
     models:
       assembly_regulator_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

