

options:
  insert_models_over_bins: true
  belt_population_cycles: 0
  insert_models_over_stations: false
  gazebo_state_logging: false
  current_gripper_type: gripper_tray
time_limit: 500



table_tray_infos:
  table_1: 
    tray_model: movable_tray_metal_shiny
    quantity: 1
  table_2: 
    tray_model: movable_tray_dark_wood
    quantity: 1


agv_infos:
  agv1:
    location: as1
    products:
      part_0:
        type: assembly_battery_blue
        pose:
          xyz: [0.15, -0.1, 0]
          rpy: [0, 0, 'pi/4']
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [0.0, 0, 0]
          rpy: [0, 0, 'pi/4']
  agv2:
    location: as1
    products:
      part_0:
        type: assembly_battery_blue
        pose:
          xyz: [-0.15, -0.1, 0]
          rpy: [0, 0, 'pi/4']
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [0.0, 0.2, 0]
          rpy: [0, 0, 'pi/4']
  agv3:
    location: as4
    products:
      part_0:
        type: assembly_pump_red
        pose:
          xyz: [-0.15, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_battery_red
        pose:
          xyz: [0.15, 0, 0]
          rpy: [0, 0, 0]
  agv4:
    location: as4
    products:
      part_0:
        type: assembly_pump_red
        pose:
          xyz: [0.15, -0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_battery_red
        pose:
          xyz: [0.15, 0.1, 0]
          rpy: [0, 0, 0] 


orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    assembly:
      shipment_count: 1
      stations: [as4]
      products:
        part_0:
          type: assembly_battery_red
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 'pi']
        part_1:
          type: assembly_pump_red
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [0, 0, 0]
  order_1:
    priority: 3
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: unwanted_products
    announcement_condition_value: 1
    assembly:
      shipment_count: 1
      stations: [as1]
      products:
        part_0:
          type: assembly_battery_blue
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [0, 0, 0]

models_over_bins:
   bin2:
     models:
       assembly_pump_green:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 'pi/3']
        num_models_x: 2
        num_models_y: 2
   bin6:
     models:
       assembly_battery_green:
        xyz_start: [0.2, 0.2, 0.0]
        xyz_end: [0.4, 0.4, 0.0]
        rpy: [0, 0, 'pi/3']
        num_models_x: 2
        num_models_y: 2
faulty_products:
  - assembly_pump_green_1
  - assembly_battery_green_2


